### ISSUE TITLE
Crear ambiente firebase

### ISSUE THREAD

**Issue by MatiPruvost** [bancodealimentoscba/ba-survey#5]
Definir el modelo de datos y validarlo con los chicos de Maps

Se necesitarían tres consultas

Pública (Lo puede hacer cualquier usuario)

- Crear org beneficiaria

Privada (Lo puede hacer un usuario específico, voluntario del BA)

- Consultar lista de org beneficiarias

- Editar org beneficiaria

**Comment by gnicolasarroyo** [comment]
Chicos, agrego la cuenta Servicios BAC para crear allí lo asociado al ambiente firebase y también agrego las cuentas de los próximos usuarios, Moderador BAC y Voluntario BAC, como habíamos acordado.

name: Servicios BAC
user: bac.servicios@gmail.com
pass: ****

name: Moderador BAC
user: bac.moderador@gmail.com
pass: ****

name: Voluntario BAC
user: bac.voluntario@gmail.com
pass: ****

No pude formalizar lo del ambiente aún, se me complico el finde, si dentro de lo posible alguien puede tomarlo sería genial, porque sigo complicado esta semana con otros temas, sino intento mañana o pasado avanzar con esto.

Los pass de las cuentas, háganme un ping en HO y se los paso. En el transcurso del día voy a estar fuera de la ofi, pero cuando me pueda conectar les respondo.

Abrazo team!.
